### ISSUE TITLE
Application crashed

### ISSUE THREAD

**Issue by UttamPanchasara** [CasperPas/flutter-sound-stream#25]
Application getting crash randomly with following error:

`Fatal Exception: java.lang.IllegalArgumentException
       at java.nio.ByteBuffer.allocate(ByteBuffer.java:281)
       at vn.casperpas.sound_stream.SoundStreamPlugin$createRecordListener$1.onPeriodicNotification(SoundStreamPlugin.kt:390)
       at android.media.AudioRecord$NativeEventHandler.handleMessage(AudioRecord.java:1932)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:227)
       at android.app.ActivityThread.main(ActivityThread.java:7822)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)`

**Comment by jarekb123** [comment]
I've also getting random crashes, but only on release mode

**Comment by amrmagdy12** [comment]
i'm getting this Error on OPPO devices only with higher API level !!

**Comment by ollex** [comment]
I have this on some devices, too. I don't exactly know where it fails, seems like a timing issue?? 
Adding a check in SoundStreamPlugkin.kt in onPeriodicNotification before creating the buffer helps to prevent the crash:
add:
`if (shortOut < 1) {
  return
}`
before `val byteBuffer = ByteBuffer.allocate(shortOut * 2)`

**Comment by CasperPas** [comment]
Thank you, @ollex 
Could someone try it out to confirm this? I'll merge the PR anyway since it's good to add the `shortOut` check

**Comment by Abdeljalil-Bouchfar** [comment]
Yes, it solves it, I was facing the same issue before I made the PR.
and Thanks to @ollex

**Comment by ollex** [comment]
Thanks, @CasperPas for starting this repo - saves one from having to include huge libraries for just doing some pcm and @Abdeljalil-Bouchfar for the PR!

**Comment by CasperPas** [comment]
Published the latest version with this fix. Thanks!
