### ISSUE TITLE
App crashed when method stop 

### ISSUE THREAD

**Issue by mengyuanfan** [CasperPas/flutter-sound-stream#60]
Shutting down VM
FATAL EXCEPTION: main
Process: com.example.xf_demo, PID: 7300
java.lang.IllegalArgumentException
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:281)
	at vn.casperpas.sound_stream.SoundStreamPlugin$createRecordListener$1.onPeriodicNotification(SoundStreamPlugin.kt:390)
	at android.media.AudioRecord$NativeEventHandler.handleMessage(AudioRecord.java:1976)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8087)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**Comment by CasperPas** [comment]
I believe it was related to this issue: https://github.com/CasperPas/flutter-sound-stream/issues/25
I'll close it. Please reopen if it's still persist. Thank you!
